### ISSUE TITLE
Remove GQ_PROFILE_MESSAGE from the requirements

### ISSUE THREAD

**Issue by maurelio1234** [andrewallred/allez#10]
It is very difficult to obtain by a normal user.
Maybe we could connect to the users' profile using GQ_PROFILE_NAME and the password on it's account.

**Comment by andrewallred** [comment]
Moving the GQ_PROFILE_MESSAGE out of the .env is easy but I'm not sure about GQ_GAME_MESSAGE, there is a token there that I think might be user specific and I'm not sure how to get it. We should compare notes @maurelio1234.

**Comment by andrewallred** [comment]
Went ahead and removed GQ_PROFILE_MESSAGE https://github.com/andrewallred/allez/commit/aea2dab1bd55aa96a7747bb1f5c936f46bc17ba0

**Comment by maurelio1234** [comment]
Nice!
Yes, I need to take a look at the ws messages again.
Maybe from a scenario where we start from scratch (like private mode) then add the user password then navigate to the profile.

**Comment by andrewallred** [comment]
@maurelio1234 I've split this into two issues. I will close this one and you can see the other one here https://github.com/andrewallred/allez/issues/11
