### ISSUE TITLE
Which license applies to this code?

### ISSUE THREAD

**Issue by maurelio1234** [andrewallred/allez#2]

**Comment by andrewallred** [comment]
@maurelio1234 I've added the MIT license, thank you for prompting me. If you are interested in contributing to this at all let me know as I'd be happy to collaborate.

**Comment by maurelio1234** [comment]
Nice! I got it working as an AWS lambda retrieving  9, 13 and 19 (still waiting them to open it again to test it) last games. I will push it to my fork later so you can see if you want to take something from it.
